version: '3'

services:
    db:
        container_name: base-mysql
        image: mysql:5.7.31
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - '3306:3306'